# Generated by Django 5.0 on 2024-03-13 01:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_remove_blog_readed_num_readnum"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReadNum",
        ),
    ]
