# Generated by Django 5.0 on 2024-03-24 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0002_alter_comment_options_comment_parent_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="parent_id",
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="comment.comment",
            ),
        ),
    ]
