# Generated by Django 5.0 on 2024-03-24 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0004_comment_reply_to_alter_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="root",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="root_comment",
                to="comment.comment",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_comment",
                to="comment.comment",
            ),
        ),
    ]
