# Generated by Django 5.0 on 2024-03-27 03:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0005_comment_root_alter_comment_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["comment_time"]},
        ),
    ]
